/**
 * User-facing directions. Templates + patterns are applied by the system;
 * the human only picks a direction and describes their situation.
 */

/** @typedef {{ id: string, label: string, blurb: string, group: string, templateId?: string, primaryVar?: string, task: string, strength: string, patterns: string[], placeholder: string, inputLabel: string }} Direction */

/** @type {Direction[]} */
export const DIRECTIONS = [
  {
    id: "freeform",
    label: "Just improve this",
    blurb: "Rewrite whatever I paste. No special shape.",
    group: "simple",
    task: "general",
    strength: "medium",
    patterns: ["constraint-stack", "definition-of-done"],
    placeholder: "Paste any rough prompt…",
    inputLabel: "Your rough prompt",
  },
  {
    id: "implement",
    label: "Build a feature",
    blurb: "Implement something in the codebase.",
    group: "coding",
    templateId: "implement-feature",
    primaryVar: "goal",
    task: "coding",
    strength: "medium",
    patterns: ["plan-then-execute", "definition-of-done"],
    placeholder: "e.g. Add a dark mode toggle to the settings page…",
    inputLabel: "What should be built?",
  },
  {
    id: "review",
    label: "Review code",
    blurb: "Security-aware review with severity and fixes.",
    group: "coding",
    templateId: "code-review",
    primaryVar: "scope",
    task: "coding",
    strength: "strong",
    patterns: ["definition-of-done"],
    placeholder: "e.g. PR #42, or src/auth/, or paste a diff description…",
    inputLabel: "What should be reviewed?",
  },
  {
    id: "debug",
    label: "Debug a bug",
    blurb: "Systematic reproduce → fix loop.",
    group: "coding",
    templateId: "debug-systematic",
    primaryVar: "symptom",
    task: "coding",
    strength: "strong",
    patterns: ["react", "plan-then-execute"],
    placeholder: "e.g. Checkout fails on Safari when cart has a discount…",
    inputLabel: "What’s going wrong?",
  },
  {
    id: "fix-error",
    label: "Fix this error",
    blurb: "Turn a stack trace / CI failure into a fix brief.",
    group: "coding",
    templateId: "fix-from-error",
    primaryVar: "error",
    task: "coding",
    strength: "medium",
    patterns: ["definition-of-done"],
    placeholder: "Paste the error log or CI failure…",
    inputLabel: "Error / log",
  },
  {
    id: "tests",
    label: "Write tests",
    blurb: "High-value tests for a module or behavior.",
    group: "coding",
    templateId: "write-tests",
    primaryVar: "subject",
    task: "coding",
    strength: "medium",
    patterns: ["definition-of-done"],
    placeholder: "e.g. the payment webhook handler…",
    inputLabel: "What needs tests?",
  },
  {
    id: "refactor",
    label: "Safe refactor",
    blurb: "Behavior-preserving cleanup.",
    group: "coding",
    templateId: "refactor-safe",
    primaryVar: "target",
    task: "coding",
    strength: "medium",
    patterns: ["plan-then-execute", "definition-of-done"],
    placeholder: "e.g. Extract the billing service from app.js…",
    inputLabel: "What should be refactored?",
  },
  {
    id: "explain",
    label: "Explain code",
    blurb: "Onboarding map of a subsystem.",
    group: "coding",
    templateId: "explain-codebase",
    primaryVar: "area",
    task: "research",
    strength: "medium",
    patterns: ["constraint-stack"],
    placeholder: "e.g. how auth sessions work in this repo…",
    inputLabel: "What area should it explain?",
  },
  {
    id: "ui",
    label: "Polish UI",
    blurb: "Frontend redesign without AI slop.",
    group: "design",
    templateId: "ui-redesign",
    primaryVar: "surface",
    task: "design",
    strength: "strong",
    patterns: ["anti-slop-ui", "definition-of-done"],
    placeholder: "e.g. the homepage hero and pricing section…",
    inputLabel: "What UI should improve?",
  },
  {
    id: "landing",
    label: "Landing page",
    blurb: "Marketing page with clear narrative.",
    group: "design",
    templateId: "landing-page",
    primaryVar: "product",
    task: "design",
    strength: "strong",
    patterns: ["anti-slop-ui", "constraint-stack"],
    placeholder: "e.g. Prompter: a local prompt workshop for coding agents…",
    inputLabel: "What product is the page for?",
  },
  {
    id: "docs",
    label: "Write docs",
    blurb: "Clear technical documentation.",
    group: "writing",
    templateId: "technical-doc",
    primaryVar: "topic",
    task: "writing",
    strength: "medium",
    patterns: ["definition-of-done"],
    placeholder: "e.g. how to run the CLI and export a skill…",
    inputLabel: "What should the docs cover?",
  },
  {
    id: "research",
    label: "Research",
    blurb: "Sourced answer with confidence and open questions.",
    group: "research",
    templateId: "deep-research",
    primaryVar: "question",
    task: "research",
    strength: "medium",
    patterns: ["chain-of-thought", "constraint-stack"],
    placeholder: "e.g. best practices for QLoRA on 24GB GPUs in 2026…",
    inputLabel: "Research question",
  },
  {
    id: "train",
    label: "Train / LoRA",
    blurb: "Fine-tune plan: data → train → eval.",
    group: "training",
    templateId: "lora-sft-plan",
    primaryVar: "base_model",
    task: "training",
    strength: "strong",
    patterns: ["evidence-first", "plan-then-execute", "definition-of-done"],
    placeholder: "e.g. Qwen2.5-7B on my SFT jsonl at data/training/… (include data path in the note)",
    inputLabel: "Model + data (be specific)",
  },
  {
    id: "pr",
    label: "PR description",
    blurb: "Human-readable pull request summary.",
    group: "coding",
    templateId: "pr-description",
    primaryVar: "changes",
    task: "writing",
    strength: "light",
    patterns: ["constraint-stack"],
    placeholder: "e.g. Added OAuth callback and fixed session cookie flags…",
    inputLabel: "What changed?",
  },
  {
    id: "mission",
    label: "Multi-step mission",
    blurb: "Long agent job with checkpoints.",
    group: "agent",
    templateId: "multi-step-mission",
    primaryVar: "mission",
    task: "coding",
    strength: "strong",
    patterns: ["plan-then-execute", "react", "definition-of-done"],
    placeholder: "e.g. Migrate the CMS to Postgres and prove tests pass…",
    inputLabel: "Mission",
  },
];

export function getDirection(id) {
  return DIRECTIONS.find((d) => d.id === id) || DIRECTIONS[0];
}

export function listDirections() {
  return DIRECTIONS.map((d) => ({
    id: d.id,
    label: d.label,
    blurb: d.blurb,
    group: d.group,
    inputLabel: d.inputLabel,
    placeholder: d.placeholder,
    hasTemplate: Boolean(d.templateId),
  }));
}
